export const HEADER_FUCOS = 'HEADER_FUCOS';
export const HEADER_BLUR = 'HEADER_BLUR';
export const HEADER_CHANNGE= 'HEADER_CHANNGE';

export const HEADER_MOUSEENTER = 'HEADER_MOUSEENTER';

export const HEADER_MOUSELEAVE = 'HEADER_MOUSELEAVE';

export const HEADER_CHANGEPAGE = 'HEADER_CHANGEPAGE';